server:
  port: 9000

logging:
  level:
    org.springframework.security: trace
    org.springframework.web: trace

spring:
  config:
    import: optional:file:.env.local[.properties]
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
